from collector import collector

def main():
    collector.GameInformationCollector("all games").run(start_index=18809)
    # collector.RelatedGamesCollector("Mario Kart 8 Deluxe").run()
    # collector.RelatedGamesCollector("Portal").run()
    # collector.RelatedGamesCollector("Getting Over it With Bennett Foddy").run()
    # collector.RelatedGamesCollector("Super Metroid").run()
    # collector.RelatedGamesCollector("ROBLOX: Speed Run 4").run()
    # collector.RelatedGamesCollector("Pou").run()
    # collector.RelatedGamesCollector("Super Mario Sunshine").run()
    # collector.RelatedGamesCollector("Super Mario World").run()
    # collector.RelatedGamesCollector("Super Mario Bros.").run()
    # collector.RelatedGamesCollector("ROBLOX: Piggy").run()
    # collector.RelatedGamesCollector("Minecraft: Bedrock Edition").run()
    # collector.RelatedGamesCollector("The Legend of Zelda: Ocarina of Time").run()
    # collector.RelatedGamesCollector("Roblox: DOORS").run()
    # collector.RelatedGamesCollector("The Legend of Zelda: A Link to the Past").run()
    # collector.RelatedGamesCollector("SpongeBob SquarePants: Battle for Bikini Bottom").run()
    # collector.RelatedGamesCollector("Resident Evil 2 (2019)").run()
    # collector.RelatedGamesCollector("Outlast").run()
    # collector.RelatedGamesCollector("Hollow Knight").run()
    # collector.RelatedGamesCollector("Hades").run()
    # collector.RelatedGamesCollector("Minecraft (Classic)").run()
    # collector.RelatedGamesCollector("The Legend of Zelda: Breath of the Wild").run()
    # collector.RelatedGamesCollector("Bhop pro").run()
    # collector.RelatedGamesCollector("Undertale").run()
    # collector.RelatedGamesCollector("Refunct").run()

if __name__ == "__main__":
    main()
